# Generated by Django 4.2.1 on 2023-05-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_link_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
