version: "3.8"
services:
  postgres:
    container_name: postgresql-db
    image: postgres:14.3-alpine
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  api:
    container_name: api
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always

