# Generated by Django 4.2.1 on 2023-05-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('-id',), 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
    ]
