# Generated by Django 4.2.1 on 2023-05-24 16:32

import django.contrib.postgres.fields
from django.db import migrations, models
import plant.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other_resources_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(unique=True), blank=True, null=True, size=5, unique=True, validators=[plant.models.validate_array_length]),
        ),
    ]
