# Generated by Django 4.2.1 on 2023-05-24 16:39

import django.contrib.postgres.fields
from django.db import migrations, models
import plant.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plant_other_resources_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other_resources_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(unique=True, validators=[plant.models.validate_link]), blank=True, null=True, size=5, unique=True, validators=[plant.models.validate_array_length]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='wikipedia_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, validators=[plant.models.validate_link], verbose_name='wikipedia_link'),
        ),
    ]
