# Generated by Django 4.2.1 on 2023-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_plant_other_resources_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'ordering': ('-id',), 'verbose_name': 'Plant Image', 'verbose_name_plural': 'Plant Images'},
        ),
    ]
