# Generated by Django 4.2.1 on 2023-05-24 17:54

from django.db import migrations, models
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_plantimage_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[utilities.validators.ImageValidator(height=300, size=512000, width=300)]),
        ),
    ]
