# Generated by Django 4.2.1 on 2023-05-24 18:49

from django.db import migrations, models
import django.db.models.deletion
import plant.models
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_alter_plantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to=plant.models.get_upload_to, validators=[utilities.validators.ImageValidator(height=300, size=512000, width=300)]),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plant.plant'),
        ),
    ]
