# Generated by Django 4.2.1 on 2023-06-02 08:05

from django.db import migrations, models
import plant.models
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_alter_plantimage_image_alter_plantimage_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to=plant.models.get_upload_to, validators=[utilities.validators.ImageValidator(size=1024000)]),
        ),
    ]
