# Generated by Django 4.2.1 on 2023-06-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_alter_plantimage_image'),
        ('plant', '0011_alter_plantspecies_genus'),
    ]

    operations = [
    ]
