# Generated by Django 4.2.2 on 2023-07-13 13:45

import django.contrib.postgres.fields
from django.db import migrations, models
import plant.models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_rename_common_name_plant_common_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='other_resources_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, validators=[plant.models.validate_link]), blank=True, null=True, size=5, validators=[plant.models.validate_array_length]),
        ),
    ]
