# Generated by Django 4.2.1 on 2023-05-11 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofile.models
import utilities.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=userprofile.models.get_upload_to, validators=[utilities.validators.ImageValidator(height=300, size=512000, width=300)])),
                ('facebook', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='facebook')),
                ('instagram', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='instagram')),
                ('linkedIn', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='linkedIn')),
                ('twitter', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='twitter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('-id',),
            },
        ),
    ]
