# Generated by Django 5.0.1 on 2024-01-09 15:17

import userprofile.models
import utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=userprofile.models.get_upload_to, validators=[utilities.validators.ImageValidator(size=4096000)]),
        ),
    ]
