# Generated by Django 4.2.2 on 2023-07-13 13:50

import contact_us.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import utilities.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_us', '0002_rename_description_contactus_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), size=5, unique=True, validators=[contact_us.models.validate_array_length])),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('medicinal_properties', django_ckeditor_5.fields.CKEditor5Field()),
                ('duration', models.CharField(choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('perennial', 'Perennial'), ('ephemeral', 'Ephemeral'), ('deciduous', 'Deciduous'), ('evergreen', 'Evergreen')], max_length=10)),
                ('growth_habit', models.CharField(choices=[('herb', 'Herb'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('graminoid', 'Graminoid'), ('subshrub', 'Subshrub'), ('vine', 'Vine')], max_length=10)),
                ('family', models.CharField(max_length=255, verbose_name='family')),
                ('genus', models.CharField(max_length=255, verbose_name='genus')),
                ('species', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='species')),
                ('image', models.ImageField(upload_to=contact_us.models.get_upload_to, validators=[utilities.validators.ImageValidator(size=1024000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ('-id',),
            },
        ),
    ]
