# Generated by Django 4.2.2 on 2023-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='common_names',
        ),
        migrations.AddField(
            model_name='feedback',
            name='common_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
